### ISSUE TITLE
[Move Prover] `module_builder.rs` panics for 'no entry found for key'

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#473]
## How to reproduce the bug
```
module 0x42::loop_inv {
    use std::vector;

    fun g() {
        let v = vector::empty<u64>();
        let i = 0;

        while (i < 5) {
            vector::push_back(&mut v, 0);
        };
        spec {
            assert true;
        };
    }
}
```

For this code, Prover produces the following error:
```
$ RUST_BACKTRACE=1 move prove -t loop_inv.move
thread 'main' panicked at 'no entry found for key', language/move-model/src/builder/module_builder.rs:743:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
   5: move_model::builder::module_builder::ModuleBuilder::def_ana
   6: move_model::builder::module_builder::ModuleBuilder::translate
   7: move_model::run_spec_checker
   8: move_model::run_model_builder_with_options
   9: move_package::compilation::model_builder::ModelBuilder::build_model
  10: move_package::BuildConfig::move_model_for_package
  11: move_cli::base::prove::run_move_prover
  12: move_cli::base::prove::Prove::execute
  13: move_cli::run_cli
  14: move_cli::move_cli
  15: move::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Expected Result
Prover terminates successfully.

**Comment by meng-xu-cs** [comment]
The reason for this panic is that the compiler is smart enough, after
constant folding and dead code elimination, to realize that
basic blocks after the `while` loop can never be reached.

Therefore, the basic blocks containing the spec block is eliminated,
causing the `NoOp` which supposed to identify the spec block to be
missing in the final bytecode.

```diff
module 0x42::loop_inv {
    use std::vector;

    fun g() {
        let v = vector::empty<u64>();
        let i = 0;

        while (i < 5) {
            vector::push_back(&mut v, 0);
        };
- // DEAD CODE ELIMINATED
-        spec {
-            assert true;
-        };
- // DEAD CODE ELIMINATED
    }
}
```

**Comment by wrwg** [comment]
Is this closed now? @rahxephon89
