### ISSUE TITLE
[evm] Compile error "error: Invalid value "ethereum" for '--arch <ARCHITECTURE>'

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#61]
```
$ npx hardhat compile
Nothing to compile
Building 14 Move packages...

Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/Native
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/Greeter
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/FortyTwo
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ExternalCall
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/Event
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC721Tradable
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC721Mock
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC20Mock
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC20DecimalsMock
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC1155Tradable
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/ERC1155Mock
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/Caller
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/Revert
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help


Failed to build /Users/jkpark/Work/move/language/evm/hardhat-examples/contracts/Token
error: Invalid value "ethereum" for '--arch <ARCHITECTURE>': Unrecognized architecture ethereum -- only "move", "async-move" are supported

For more information try --help

An unexpected error occurred:

Error: Failed to build one or more Move packages
    at SimpleTaskDefinition.action (/Users/jkpark/Work/move/language/evm/hardhat-move/src/index.ts:388:19)
    at Environment._runTaskDefinition (/Users/jkpark/Work/move/language/evm/hardhat-examples/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/jkpark/Work/move/language/evm/hardhat-examples/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/Users/jkpark/Work/move/language/evm/hardhat-examples/node_modules/hardhat/src/builtin-tasks/compile.ts:1422:7)
    at Environment._runTaskDefinition (/Users/jkpark/Work/move/language/evm/hardhat-examples/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/jkpark/Work/move/language/evm/hardhat-examples/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at main (/Users/jkpark/Work/move/language/evm/hardhat-examples/node_modules/hardhat/src/internal/cli/cli.ts:218:5)
```

**Comment by junkil-park** [comment]
The error will go away if `move-cli` is installed with the `evm-backend` feature (`cargo install --path . --features evm-backend`).
