### ISSUE TITLE
[Bug][Prover] generic axiom cause a panic

### ISSUE THREAD

**Issue by junkil-park** [move-language/move#632]
To reproduce:

1. Add the following spec to `aptos-core/aptos-move/framework/aptos-stdlib/sources/hash.spec.move`.
```
    spec module {
         fun generic_injection<T>(x: T): u64;
         axiom<T> forall v1: T, v2: T: v1 == v2 <==> generic_injection(v1) == generic_injection(v2);
    }
```

2. Run `move prove` or `aptos move prove` in `aptos-core/aptos-move/framework/aptos-stdlib`

No error is expected, but the following error is produced:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', language/move-model/src/ty.rs:299:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:84:5
   3: move_model::ty::Type::replace
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: move_model::ty::Type::replace
   6: move_model::ty::Type::replace
   7: move_prover_boogie_backend::spec_translator::SpecTranslator::translate_quant
   8: move_prover_boogie_backend::spec_translator::SpecTranslator::translate_exp
   9: move_prover_boogie_backend::spec_translator::SpecTranslator::translate
  10: move_prover_boogie_backend::spec_translator::SpecTranslator::translate_axioms
  11: move_prover_boogie_backend::bytecode_translator::BoogieTranslator::translate
  12: move_prover::generate_boogie
  13: move_prover::run_move_prover_with_model
  14: move_cli::base::prove::run_move_prover
  15: move_cli::base::prove::Prove::execute
  16: move_cli::run_cli
  17: move_cli::move_cli
  18: move::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rahxephon89** [comment]
Here is a simplified example:
```
  module aptos_std::Test {
    struct S<phantom K, phantom V> {
    }

    public fun f<K, V>(): S<K, V> {
        S {
        }
    }

    spec module {
        axiom<T> forall v1: T: true;
    }
}
```
