### ISSUE TITLE
[Bug] crash in hlir translate phase of compiler

### ISSUE THREAD

**Issue by sblackshear** [move-language/move#687]
# 🐛 Bug

Hey guys, I am in the process of splitting my functionality from one module into two and while doing so I keep running into this error:

```
2022-11-22T20:46:50.609834Z ERROR telemetry_subscribers: panicked at 'called Option::unwrap() on a None value', /home/collin/.cargo/git/checkouts/move-0639dd674f581c30/0800fc7/language/move-compiler/src/hlir/translate.rs:1249:29 panic.file="/home/collin/.cargo/git/checkouts/move-0639dd674f581c30/0800fc7/language/move-compiler/src/hlir/translate.rs" panic.line=1249 panic.column=29
thread 'main' panicked at 'called Option::unwrap() on a None value', /home/collin/.cargo/git/checkouts/move-0639dd674f581c30/0800fc7/language/move-compiler/src/hlir/translate.rs:1249:29
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: move_compiler::hlir::translate::exp_impl
   4: move_compiler::hlir::translate::exp_::exp_loop
   5: move_compiler::hlir::translate::exp_
   6: move_compiler::hlir::translate::block
   7: move_compiler::hlir::translate::function_body_defined
   8: move_compiler::hlir::translate::function
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  12: move_compiler::shared::unique_map::UniqueMap<K,V>::maybe_from_iter
  13: move_compiler::hlir::translate::program
  14: move_compiler::command_line::compiler::run
  15: move_compiler::command_line::compiler::run
  16: move_compiler::command_line::compiler::run
  17: move_compiler::command_line::compiler::run
  18: move_compiler::command_line::compiler::SteppedCompiler<_>::run
  19: move_compiler::command_line::compiler::Compiler::run
  20: move_compiler::command_line::compiler::Compiler::build
  21: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  22: move_package::compilation::compiled_package::CompiledPackage::build_all
  23: move_package::compilation::build_plan::BuildPlan::compile_no_exit
  24: move_package::BuildConfig::compile_package_no_exit
  25: sui_framework_build::compiled_package::BuildConfig::build
  26: sui_framework::build_move_package
  27: sui::sui_move::build::Build::execute_internal
  28: sui::sui_move::build::Build::execute
  29: sui::sui_move::execute_move_command
  30: sui::sui_commands::SuiCommand::execute::{{closure}}
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  32: tokio::park::thread::CachedParkThread::block_on
  33: tokio::runtime::Runtime::block_on
  34: sui::main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
Aborted
```

**Comment by admin-aftermath** [comment]
Here's some more info on the matter: 

(1) I think it has to do with the number of function calls to another module. It seems to happen when the number of calls to the second module hits 50. If I comment out even one line that calls a function from the second module it will get past this issue and show me expected errors.
(2) I am separating the two modules into an interface and a module that will contain my domain-specific structs. Because of this there are a lot of getters/setters that are called from my interface.

**Comment by tnowacki** [comment]
You can give me a big blob of modules if it's easier, that's fine.

**Comment by admin-aftermath** [comment]
> You can give me a big blob of modules if it's easier, that's fine.

Thanks for looking into this Todd - I added you to the repo that this issue is coming from

**Comment by tnowacki** [comment]
Fix is up, was a fun one :) 

But to unblock yourself @admin-aftermath, you cannot construct structs outside of the module where they are defined. You just found some weird code that tried to handle that case when it happened.

**Comment by admin-aftermath** [comment]
Thanks @tnowacki. Yeah sorry for the mess, I am doing one large refactoring and haven't added the constructors yet. One error at a time lol

**Comment by tnowacki** [comment]
Wasn't much of a mess at all! the size of the test doesn't really matter much as long as I can print shit out inside the compiler... which I can ;)
